apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate

metadata:
  name: frontend-success-rate
  namespace: frontend

spec:
  metrics:
    - name: success-rate

      interval: 15s
      count: 4

      failureLimit: 1

      successCondition: result[0] >= 0.95

      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090

          query: |
            sum(
              rate(
                flask_http_requests_total{
                  service="frontend-canary",
                  status=~"2..",
                  exported_endpoint!="/metrics"
                }[2m]
              )
            )
            /
            sum(
              rate(
                flask_http_requests_total{
                  service="frontend-canary",
                  exported_endpoint!="/metrics"
                }[2m]
              )
            )
