apiVersion: v1
kind: Service

metadata:
  name: frontend-canary
  namespace: frontend
  labels:
    app: frontend

spec:

  selector:
    app: frontend

  ports:

    - name: http
      port: 5000
      targetPort: http
