apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - frontend

  selector:
    matchLabels:
      app: frontend

  endpoints:
    - port: http
      path: /metrics
      interval: 10s
